// src/lib/data.ts

// 'pl' (Lehçe) eklendi
export type Language = "tr" | "en" | "es" | "fr" | "pl";

export const dictionaries = {
  tr: {
    navHome: "Ana Sayfa",
    navChat: "Sohbet",
    navLearn: "Öğren",
    navProfile: "Profil",
    loading: "Yükleniyor...",
    save: "Değişiklikleri Kaydet",
    back: "Geri",
    welcome: "Tekrar hoş geldin,",
    companyStatus: "Şirket Durumu",
    breakTime: "Mola Vakti",
    unreadMessages: "Okunmamış Mesaj",
    pendingTasks: "Bekleyen Görev",
    cultureTest: "Kültür Testi",
    completeSimulation: "Haftalık simülasyonunu tamamla.",
    globalChat: "Global Takım Sohbeti",
    typeMessage: "Mesaj yaz...",
    myTasks: "Görevlerim",
    todayTasks: "Bugün yapılacak işler:",
    addTaskPlaceholder: "Yeni bir görev ekle...",
    todo: "Yapılacaklar",
    completed: "Tamamlananlar",
    greatJob: "Harika! Her şey tamamlandı. 🎉",
    confirmDelete: "Bu görevi silmek istediğine emin misin?",
    profile: "Profil",
    photoNotice:
      "Fotoğrafı değiştirmek için yukarıdaki profil ikonunu kullanın.",
    settings: "Ayarlar",
    language: "Uygulama Dili",
    culture: "Kültürel Bölge",
    religion: "Din / İnanç",
    religionNotice: "Mola saatleri ve bayramlar buna göre ayarlanır.",
    quizTitle: "Kültürel Simülasyon",
    quizDesc: "Polonya, İspanya, Fas ve Türkiye iş kültürünü deneyimle.",
    generalPerformance: "Genel Performans",
    game: "Oyun",
    avgScore: "Ort. Puan",
    question: "SORU",
    score: "Puan",
    nextQuestion: "Sonraki Soru",
    quizCompleted: "Simülasyon Tamamlandı!",
    totalScore: "Toplam Puanın:",
    playAgain: "Tekrar Oyna",
    correct: "Doğru!",
    wrong: "Yanlış!",
    scheduleTitle: "Zaman & Gelenekler",
    today: "Bugün",
    workingHour: "Şu an: Çalışma Saati",
    dailyFlow: "Günlük Akışım",
    startShift: "Mesai Başlangıcı",
    lunch: "Öğle Yemeği",
    prayerTime: "İbadet / Kişisel Mola",
    rulesTitle: "Kurallar & İşleyiş",
    expectations: "Kültürel Beklentiler",
    mandatory: "Zorunlu",
    flexible: "Esnek",
    videos: "Video Rehberler",
    supportTitle: "Destek & Arabuluculuk",
    mediationNeed: "Arabulucuya İhtiyacım Var",
    mediationDesc: "Bir çatışma mı yaşıyorsunuz? Güvenli ortamda çözelim.",
    createTicket: "Talep Oluştur",
    contactHR: "HR ile Görüş",
    surveys: "Hızlı Anketler",
  },
  en: {
    navHome: "Home",
    navChat: "Chat",
    navLearn: "Learn",
    navProfile: "Profile",
    loading: "Loading...",
    save: "Save Changes",
    back: "Back",
    welcome: "Welcome back,",
    companyStatus: "Company Status",
    breakTime: "Break Time",
    unreadMessages: "Unread Messages",
    pendingTasks: "Pending Tasks",
    cultureTest: "Culture Test",
    completeSimulation: "Complete your weekly simulation.",
    globalChat: "Global Team Chat",
    typeMessage: "Type a message...",
    myTasks: "My Tasks",
    todayTasks: "Tasks for today:",
    addTaskPlaceholder: "Add a new task...",
    todo: "To Do",
    completed: "Completed",
    greatJob: "Great! All done. 🎉",
    confirmDelete: "Are you sure you want to delete this task?",
    profile: "Profile",
    photoNotice: "Use the profile icon above to change your photo.",
    settings: "Settings",
    language: "App Language",
    culture: "Cultural Region",
    religion: "Religion / Belief",
    religionNotice: "Break times and holidays are adjusted accordingly.",
    quizTitle: "Cultural Simulation",
    quizDesc:
      "Experience business culture in Poland, Spain, Morocco, and Turkey.",
    generalPerformance: "Performance",
    game: "Games",
    avgScore: "Avg. Score",
    question: "QUESTION",
    score: "Score",
    nextQuestion: "Next Question",
    quizCompleted: "Simulation Completed!",
    totalScore: "Your Total Score:",
    playAgain: "Play Again",
    correct: "Correct!",
    wrong: "Wrong!",
    scheduleTitle: "Time & Traditions",
    today: "Today",
    workingHour: "Now: Working Hours",
    dailyFlow: "Daily Flow",
    startShift: "Shift Start",
    lunch: "Lunch Break",
    prayerTime: "Prayer / Personal Break",
    rulesTitle: "Rules & Process",
    expectations: "Cultural Expectations",
    mandatory: "Mandatory",
    flexible: "Flexible",
    videos: "Video Guides",
    supportTitle: "Support & Mediation",
    mediationNeed: "I Need Mediation",
    mediationDesc: "Facing a conflict? Let's resolve it in a safe space.",
    createTicket: "Create Ticket",
    contactHR: "Contact HR",
    surveys: "Quick Surveys",
  },
  es: {
    navHome: "Inicio",
    navChat: "Chat",
    navLearn: "Aprender",
    navProfile: "Perfil",
    loading: "Cargando...",
    save: "Guardar Cambios",
    back: "Atrás",
    welcome: "Bienvenido de nuevo,",
    companyStatus: "Estado de la Empresa",
    breakTime: "Hora de descanso",
    unreadMessages: "Mensajes no leídos",
    pendingTasks: "Tareas pendientes",
    cultureTest: "Prueba Cultural",
    completeSimulation: "Completa tu simulación semanal.",
    globalChat: "Chat Global",
    typeMessage: "Escribe un mensaje...",
    myTasks: "Mis Tareas",
    todayTasks: "Tareas para hoy:",
    addTaskPlaceholder: "Añadir nueva tarea...",
    todo: "Por hacer",
    completed: "Completado",
    greatJob: "¡Genial! Todo listo. 🎉",
    confirmDelete: "¿Estás seguro de que quieres borrar esta tarea?",
    profile: "Perfil",
    photoNotice: "Usa el icono de perfil arriba para cambiar tu foto.",
    settings: "Ajustes",
    language: "Idioma",
    culture: "Región Cultural",
    religion: "Religión",
    religionNotice: "Los descansos y festivos se ajustan según esto.",
    quizTitle: "Simulación Cultural",
    quizDesc:
      "Experimenta la cultura de negocios en Polonia, España, Marruecos y Turquía.",
    generalPerformance: "Rendimiento",
    game: "Juegos",
    avgScore: "Puntaje Prom.",
    question: "PREGUNTA",
    score: "Puntaje",
    nextQuestion: "Siguiente Pregunta",
    quizCompleted: "¡Simulación Completada!",
    totalScore: "Puntaje Total:",
    playAgain: "Jugar de nuevo",
    correct: "¡Correcto!",
    wrong: "¡Incorrecto!",
    scheduleTitle: "Tiempo y Tradiciones",
    today: "Hoy",
    workingHour: "Ahora: Horas Laborales",
    dailyFlow: "Flujo Diario",
    startShift: "Inicio de Jornada",
    lunch: "Almuerzo",
    prayerTime: "Oración / Descanso Personal",
    rulesTitle: "Reglas y Procesos",
    expectations: "Expectativas Culturales",
    mandatory: "Obligatorio",
    flexible: "Flexible",
    videos: "Video Guías",
    supportTitle: "Soporte y Mediación",
    mediationNeed: "Necesito Mediación",
    mediationDesc: "¿Tienes un conflicto? Resolvámoslo en un espacio seguro.",
    createTicket: "Crear Ticket",
    contactHR: "Contactar RRHH",
    surveys: "Encuestas Rápidas",
  },
  fr: {
    navHome: "Accueil",
    navChat: "Chat",
    navLearn: "Apprendre",
    navProfile: "Profil",
    loading: "Chargement...",
    save: "Sauvegarder",
    back: "Retour",
    welcome: "Bon retour,",
    companyStatus: "Statut de l'entreprise",
    breakTime: "Temps de pause",
    unreadMessages: "Messages non lus",
    pendingTasks: "Tâches en attente",
    cultureTest: "Test Culturel",
    completeSimulation: "Complétez votre simulation hebdomadaire.",
    globalChat: "Chat d'équipe",
    typeMessage: "Écrivez un message...",
    myTasks: "Mes Tâches",
    todayTasks: "Tâches pour aujourd'hui :",
    addTaskPlaceholder: "Ajouter une nouvelle tâche...",
    todo: "À faire",
    completed: "Terminé",
    greatJob: "Super ! Tout est fini. 🎉",
    confirmDelete: "Êtes-vous sûr de vouloir supprimer cette tâche ?",
    profile: "Profil",
    photoNotice:
      "Utilisez l'icône de profil ci-dessus pour changer votre photo.",
    settings: "Paramètres",
    language: "Langue",
    culture: "Région Culturelle",
    religion: "Religion",
    religionNotice:
      "Les pauses et les jours fériés sont ajustés en conséquence.",
    quizTitle: "Simulation Culturelle",
    quizDesc:
      "Découvrez la culture d'entreprise en Pologne, Espagne, Maroc et Turquie.",
    generalPerformance: "Performance",
    game: "Jeux",
    avgScore: "Score Moy.",
    question: "QUESTION",
    score: "Score",
    nextQuestion: "Question Suivante",
    quizCompleted: "Simulation Terminée !",
    totalScore: "Votre Score Total :",
    playAgain: "Rejouer",
    correct: "Correct !",
    wrong: "Faux !",
    scheduleTitle: "Temps et Traditions",
    today: "Aujourd'hui",
    workingHour: "Maintenant : Heures de travail",
    dailyFlow: "Flux Quotidien",
    startShift: "Début de quart",
    lunch: "Déjeuner",
    prayerTime: "Prière / Pause Personnelle",
    rulesTitle: "Règles et Processus",
    expectations: "Attentes Culturelles",
    mandatory: "Obligatoire",
    flexible: "Flexible",
    videos: "Guides Vidéo",
    supportTitle: "Support et Médiation",
    mediationNeed: "J'ai besoin de médiation",
    mediationDesc: "Un conflit ? Résolvons-le dans un espace sûr.",
    createTicket: "Créer un ticket",
    contactHR: "Contacter RH",
    surveys: "Sondages Rapides",
  },
  pl: {
    navHome: "Start",
    navChat: "Czat",
    navLearn: "Nauka",
    navProfile: "Profil",
    loading: "Ładowanie...",
    save: "Zapisz Zmiany",
    back: "Wstecz",
    welcome: "Witaj ponownie,",
    companyStatus: "Status Firmy",
    breakTime: "Przerwa",
    unreadMessages: "Nieprzeczytane",
    pendingTasks: "Oczekujące Zadania",
    cultureTest: "Test Kulturowy",
    completeSimulation: "Ukończ cotygodniową symulację.",
    globalChat: "Czat Zespołowy",
    typeMessage: "Wpisz wiadomość...",
    myTasks: "Moje Zadania",
    todayTasks: "Zadania na dziś:",
    addTaskPlaceholder: "Dodaj nowe zadanie...",
    todo: "Do Zrobienia",
    completed: "Ukończone",
    greatJob: "Świetnie! Wszystko gotowe. 🎉",
    confirmDelete: "Czy na pewno chcesz usunąć to zadanie?",
    profile: "Profil",
    photoNotice: "Użyj ikony profilu powyżej, aby zmienić zdjęcie.",
    settings: "Ustawienia",
    language: "Język Aplikacji",
    culture: "Region Kulturowy",
    religion: "Religia / Wyznanie",
    religionNotice: "Godziny przerw i święta są odpowiednio dostosowane.",
    quizTitle: "Symulacja Kulturowa",
    quizDesc: "Poznaj kulturę biznesu w Polsce, Hiszpanii, Maroku i Turcji.",
    generalPerformance: "Wydajność",
    game: "Gry",
    avgScore: "Śr. Wynik",
    question: "PYTANIE",
    score: "Wynik",
    nextQuestion: "Następne Pytanie",
    quizCompleted: "Symulacja Zakończona!",
    totalScore: "Twój Całkowity Wynik:",
    playAgain: "Zagraj Ponownie",
    correct: "Dobrze!",
    wrong: "Źle!",
    scheduleTitle: "Czas i Tradycje",
    today: "Dzisiaj",
    workingHour: "Teraz: Godziny Pracy",
    dailyFlow: "Plan Dnia",
    startShift: "Początek Zmiany",
    lunch: "Przerwa na Lunch",
    prayerTime: "Modlitwa / Przerwa",
    rulesTitle: "Zasady i Procesy",
    expectations: "Oczekiwania Kulturowe",
    mandatory: "Obowiązkowe",
    flexible: "Elastyczne",
    videos: "Wideo Poradniki",
    supportTitle: "Wsparcie i Mediacja",
    mediationNeed: "Potrzebuję Mediacji",
    mediationDesc: "Masz konflikt? Rozwiążmy go w bezpiecznym miejscu.",
    createTicket: "Utwórz Zgłoszenie",
    contactHR: "Kontakt z HR",
    surveys: "Szybkie Ankiety",
  },
};

export interface Question {
  id: number;
  text: string;
  options: { id: string; text: string; isCorrect: boolean; feedback: string }[];
}

// 5 DILDE, 10 TANE KÜLTÜR SORUSU (PL, ES, MA, TR ODAKLI)
export const quizzes: Record<Language, Question[]> = {
  tr: [
    {
      id: 1,
      text: "(Polonya) Toplantıya 5 dakika geç kaldın. Nasıl davranmalısın?",
      options: [
        {
          id: "a",
          text: "Şakaya vurup gülümserim.",
          isCorrect: false,
          feedback: "Polonya'da dakiklik ciddidir, şaka saygısızlık olur.",
        },
        {
          id: "b",
          text: "Kısa ve net bir özür dileyip yerime geçerim.",
          isCorrect: true,
          feedback: "Doğru. Profesyonel ve ciddi bir özür beklenir.",
        },
        {
          id: "c",
          text: "Trafiği bahane ederim.",
          isCorrect: false,
          feedback: "Bahaneler profesyonel bulunmaz.",
        },
      ],
    },
    {
      id: 2,
      text: "(Polonya) Bir yöneticiye hitap ederken hangisini kullanmalısın?",
      options: [
        {
          id: "a",
          text: "Sadece ismiyle (Örn: Marek)",
          isCorrect: false,
          feedback: "Çok samimi bulunur.",
        },
        {
          id: "b",
          text: "Pan (Bay) / Pani (Bayan) + Soyadı",
          isCorrect: true,
          feedback: "Doğru. Resmiyet Polonya'da önemlidir.",
        },
        {
          id: "c",
          text: "Hey dostum!",
          isCorrect: false,
          feedback: "Kaba kabul edilir.",
        },
      ],
    },
    {
      id: 3,
      text: "(İspanya) Öğle yemeği molası genellikle ne zaman yapılır?",
      options: [
        {
          id: "a",
          text: "12:00 - 13:00",
          isCorrect: false,
          feedback: "İspanya için çok erken.",
        },
        {
          id: "b",
          text: "14:00 - 16:00 arası",
          isCorrect: true,
          feedback: "Doğru. Siesta kültürü nedeniyle yemekler geç yenir.",
        },
        {
          id: "c",
          text: "Yemek yemem.",
          isCorrect: false,
          feedback: "Sosyal ilişkiler için yemek önemlidir.",
        },
      ],
    },
    {
      id: 4,
      text: "(İspanya) Biri konuşurken sözünü keserse bu ne anlama gelir?",
      options: [
        {
          id: "a",
          text: "Saygısızlık yapıyordur.",
          isCorrect: false,
          feedback: "Genellikle değil.",
        },
        {
          id: "b",
          text: "Konuya ilgi duyuyor ve heyecanlıdır.",
          isCorrect: true,
          feedback: "Doğru. Akdeniz kültüründe bu aktif dinlemedir.",
        },
        {
          id: "c",
          text: "Seni susturmak istiyordur.",
          isCorrect: false,
          feedback: "Yanlış yorum.",
        },
      ],
    },
    {
      id: 5,
      text: "(Fas) Biri sana nane çayı ikram etti. Ne yapmalısın?",
      options: [
        {
          id: "a",
          text: "Tokum diyip reddetmeliyim.",
          isCorrect: false,
          feedback: "Fas kültüründe ikramı reddetmek kabalıktır.",
        },
        {
          id: "b",
          text: "Mutlaka kabul etmeli ve teşekkür etmeliyim.",
          isCorrect: true,
          feedback: "Doğru. Çay misafirperverliğin sembolüdür.",
        },
        {
          id: "c",
          text: "Parasını ödemeyi teklif ederim.",
          isCorrect: false,
          feedback: "Hakaret gibi algılanabilir.",
        },
      ],
    },
    {
      id: 6,
      text: "(Fas) Yemek yerken veya selamlaşırken hangi el kullanılır?",
      options: [
        {
          id: "a",
          text: "Sol el",
          isCorrect: false,
          feedback: "Sol el temizlik içindir, yemek için değil.",
        },
        {
          id: "b",
          text: "Sağ el",
          isCorrect: true,
          feedback: "Doğru. Sağ el temiz kabul edilir.",
        },
        {
          id: "c",
          text: "Fark etmez.",
          isCorrect: false,
          feedback: "Kültürel olarak çok fark eder.",
        },
      ],
    },
    {
      id: 7,
      text: "(Türkiye) Bir senden yaşça büyük bir yönetici odaya girdi.",
      options: [
        {
          id: "a",
          text: "İstifimi bozmadan otururum.",
          isCorrect: false,
          feedback: "Saygısızlık olabilir.",
        },
        {
          id: "b",
          text: "Duruşumu düzeltir, gerekirse ayağa kalkarım.",
          isCorrect: true,
          feedback: "Doğru. Hiyerarşi ve yaşa saygı önemlidir.",
        },
        {
          id: "c",
          text: "Odayı terk ederim.",
          isCorrect: false,
          feedback: "Yanlış.",
        },
      ],
    },
    {
      id: 8,
      text: "(Türkiye) Yemekten sonra 'Eline sağlık' ne demektir?",
      options: [
        {
          id: "a",
          text: "Yemeği yapan kişiye teşekkür etmek.",
          isCorrect: true,
          feedback: "Doğru. Minnet ifadesidir.",
        },
        {
          id: "b",
          text: "Ellerini yıka demek.",
          isCorrect: false,
          feedback: "Alakası yok.",
        },
        {
          id: "c",
          text: "Hesabı öde demek.",
          isCorrect: false,
          feedback: "Yanlış.",
        },
      ],
    },
    {
      id: 9,
      text: "(Polonya) Eve misafirliğe giderken ne yapmalısın?",
      options: [
        {
          id: "a",
          text: "Ayakkabılarınla girmelisin.",
          isCorrect: false,
          feedback: "Ayakkabılar çıkarılır.",
        },
        {
          id: "b",
          text: "Ayakkabılarını çıkarıp, küçük bir hediye vermelisin.",
          isCorrect: true,
          feedback: "Doğru. Çiçek veya çikolata makbule geçer.",
        },
        {
          id: "c",
          text: "Kendi yiyeceğini getirmelisin.",
          isCorrect: false,
          feedback: "Gerekmez.",
        },
      ],
    },
    {
      id: 10,
      text: "Farklı kültürlerdeki bir takımda en önemli yetenek nedir?",
      options: [
        {
          id: "a",
          text: "Sadece İngilizce bilmek.",
          isCorrect: false,
          feedback: "Yetersiz.",
        },
        {
          id: "b",
          text: "Kültürel Zeka (CQ) ve Empati.",
          isCorrect: true,
          feedback: "Doğru. Farklılıkları yönetmek esastır.",
        },
        {
          id: "c",
          text: "Kendi kültürünü dayatmak.",
          isCorrect: false,
          feedback: "Çatışma yaratır.",
        },
      ],
    },
  ],

  en: [
    {
      id: 1,
      text: "(Poland) You are 5 minutes late to a meeting. What should you do?",
      options: [
        {
          id: "a",
          text: "Joke about it and smile.",
          isCorrect: false,
          feedback: "Punctuality is critical; joking is disrespectful.",
        },
        {
          id: "b",
          text: "Apologize briefly and take your seat.",
          isCorrect: true,
          feedback: "Correct. A professional apology is expected.",
        },
        {
          id: "c",
          text: "Blame the traffic.",
          isCorrect: false,
          feedback: "Excuses are unprofessional.",
        },
      ],
    },
    {
      id: 2,
      text: "(Poland) How should you address a manager?",
      options: [
        {
          id: "a",
          text: "By first name only.",
          isCorrect: false,
          feedback: "Too informal.",
        },
        {
          id: "b",
          text: "Pan (Mr) / Pani (Ms) + Surname",
          isCorrect: true,
          feedback: "Correct. Formalities are important.",
        },
        { id: "c", text: "Hey buddy!", isCorrect: false, feedback: "Rude." },
      ],
    },
    {
      id: 3,
      text: "(Spain) When is lunch typically served?",
      options: [
        {
          id: "a",
          text: "12:00 - 13:00",
          isCorrect: false,
          feedback: "Too early for Spain.",
        },
        {
          id: "b",
          text: "Between 14:00 - 16:00",
          isCorrect: true,
          feedback: "Correct. Due to Siesta culture.",
        },
        {
          id: "c",
          text: "I skip lunch.",
          isCorrect: false,
          feedback: "Socializing over food is vital.",
        },
      ],
    },
    {
      id: 4,
      text: "(Spain) If someone interrupts you, what does it mean?",
      options: [
        {
          id: "a",
          text: "They disrespect you.",
          isCorrect: false,
          feedback: "Not usually.",
        },
        {
          id: "b",
          text: "They are engaged and interested.",
          isCorrect: true,
          feedback: "Correct. It's active listening in Mediterranean culture.",
        },
        {
          id: "c",
          text: "They want to fight.",
          isCorrect: false,
          feedback: "Wrong.",
        },
      ],
    },
    {
      id: 5,
      text: "(Morocco) Offered mint tea? What to do?",
      options: [
        {
          id: "a",
          text: "Refuse, say you're full.",
          isCorrect: false,
          feedback: "Refusing is rude.",
        },
        {
          id: "b",
          text: "Accept and thank them.",
          isCorrect: true,
          feedback: "Correct. Tea symbolizes hospitality.",
        },
        {
          id: "c",
          text: "Offer to pay.",
          isCorrect: false,
          feedback: "Insulting.",
        },
      ],
    },
    {
      id: 6,
      text: "(Morocco) Which hand to use for eating?",
      options: [
        {
          id: "a",
          text: "Left hand",
          isCorrect: false,
          feedback: "Left hand is considered unclean.",
        },
        { id: "b", text: "Right hand", isCorrect: true, feedback: "Correct." },
        {
          id: "c",
          text: "Either.",
          isCorrect: false,
          feedback: "Culturally incorrect.",
        },
      ],
    },
    {
      id: 7,
      text: "(Turkey) An older manager enters. You:",
      options: [
        {
          id: "a",
          text: "Stay slouched in your chair.",
          isCorrect: false,
          feedback: "Disrespectful.",
        },
        {
          id: "b",
          text: "Sit up straight or stand up.",
          isCorrect: true,
          feedback: "Correct. Respect for hierarchy.",
        },
        { id: "c", text: "Leave.", isCorrect: false, feedback: "Wrong." },
      ],
    },
    {
      id: 8,
      text: "(Turkey) 'Eline sağlık' means:",
      options: [
        {
          id: "a",
          text: "Thank you to the cook.",
          isCorrect: true,
          feedback: "Correct. Health to your hands.",
        },
        {
          id: "b",
          text: "Wash your hands.",
          isCorrect: false,
          feedback: "No.",
        },
        { id: "c", text: "Pay the bill.", isCorrect: false, feedback: "No." },
      ],
    },
    {
      id: 9,
      text: "(Poland) Visiting a home. What to do?",
      options: [
        {
          id: "a",
          text: "Keep shoes on.",
          isCorrect: false,
          feedback: "Shoes off usually.",
        },
        {
          id: "b",
          text: "Take shoes off, bring a small gift.",
          isCorrect: true,
          feedback: "Correct etiquette.",
        },
        {
          id: "c",
          text: "Bring your own food.",
          isCorrect: false,
          feedback: "Unnecessary.",
        },
      ],
    },
    {
      id: 10,
      text: "Most important skill in a global team?",
      options: [
        {
          id: "a",
          text: "Speaking only English.",
          isCorrect: false,
          feedback: "Insufficient.",
        },
        {
          id: "b",
          text: "Cultural Intelligence (CQ).",
          isCorrect: true,
          feedback: "Correct. Adapting is key.",
        },
        {
          id: "c",
          text: "Forcing your culture.",
          isCorrect: false,
          feedback: "Creates conflict.",
        },
      ],
    },
  ],

  es: [
    {
      id: 1,
      text: "(Polonia) Llegas 5 minutos tarde. ¿Qué haces?",
      options: [
        {
          id: "a",
          text: "Bromear.",
          isCorrect: false,
          feedback: "La puntualidad es crítica.",
        },
        {
          id: "b",
          text: "Disculparse brevemente.",
          isCorrect: true,
          feedback: "Correcto. Se espera seriedad.",
        },
        {
          id: "c",
          text: "Culpar al tráfico.",
          isCorrect: false,
          feedback: "Excusas no sirven.",
        },
      ],
    },
    {
      id: 2,
      text: "(Polonia) ¿Cómo dirigirse a un gerente?",
      options: [
        {
          id: "a",
          text: "Solo por nombre.",
          isCorrect: false,
          feedback: "Muy informal.",
        },
        {
          id: "b",
          text: "Pan (Sr) / Pani (Sra) + Apellido",
          isCorrect: true,
          feedback: "Correcto. La formalidad importa.",
        },
        {
          id: "c",
          text: "¡Hola amigo!",
          isCorrect: false,
          feedback: "Grosero.",
        },
      ],
    },
    {
      id: 3,
      text: "(España) ¿A qué hora es el almuerzo?",
      options: [
        {
          id: "a",
          text: "12:00 - 13:00",
          isCorrect: false,
          feedback: "Muy temprano.",
        },
        {
          id: "b",
          text: "Entre 14:00 - 16:00",
          isCorrect: true,
          feedback: "Correcto. Horario típico.",
        },
        {
          id: "c",
          text: "No almuerzo.",
          isCorrect: false,
          feedback: "La comida es social.",
        },
      ],
    },
    {
      id: 4,
      text: "(España) Si te interrumpen al hablar:",
      options: [
        {
          id: "a",
          text: "Es falta de respeto.",
          isCorrect: false,
          feedback: "No siempre.",
        },
        {
          id: "b",
          text: "Muestran interés y pasión.",
          isCorrect: true,
          feedback: "Correcto. Es escucha activa.",
        },
        {
          id: "c",
          text: "Quieren pelear.",
          isCorrect: false,
          feedback: "Falso.",
        },
      ],
    },
    {
      id: 5,
      text: "(Marruecos) ¿Te ofrecen té? ¿Qué haces?",
      options: [
        {
          id: "a",
          text: "Rechazar.",
          isCorrect: false,
          feedback: "Es grosero.",
        },
        {
          id: "b",
          text: "Aceptar y agradecer.",
          isCorrect: true,
          feedback: "Correcto. Símbolo de hospitalidad.",
        },
        {
          id: "c",
          text: "Pagar por él.",
          isCorrect: false,
          feedback: "Insultante.",
        },
      ],
    },
    {
      id: 6,
      text: "(Marruecos) ¿Qué mano usar para comer?",
      options: [
        { id: "a", text: "Izquierda", isCorrect: false, feedback: "Impura." },
        { id: "b", text: "Derecha", isCorrect: true, feedback: "Correcto." },
        {
          id: "c",
          text: "Cualquiera.",
          isCorrect: false,
          feedback: "Error cultural.",
        },
      ],
    },
    {
      id: 7,
      text: "(Turquía) Entra un gerente mayor.",
      options: [
        {
          id: "a",
          text: "Seguir igual.",
          isCorrect: false,
          feedback: "Irrespetuoso.",
        },
        {
          id: "b",
          text: "Enderezarse o levantarse.",
          isCorrect: true,
          feedback: "Correcto. Respeto a la jerarquía.",
        },
        { id: "c", text: "Salir.", isCorrect: false, feedback: "Mal." },
      ],
    },
    {
      id: 8,
      text: "(Turquía) 'Eline sağlık' significa:",
      options: [
        {
          id: "a",
          text: "Gracias al cocinero.",
          isCorrect: true,
          feedback: "Correcto.",
        },
        { id: "b", text: "Lava tus manos.", isCorrect: false, feedback: "No." },
        { id: "c", text: "Paga la cuenta.", isCorrect: false, feedback: "No." },
      ],
    },
    {
      id: 9,
      text: "(Polonia) Visita a una casa.",
      options: [
        {
          id: "a",
          text: "Zapatos puestos.",
          isCorrect: false,
          feedback: "No.",
        },
        {
          id: "b",
          text: "Quitar zapatos, llevar regalo.",
          isCorrect: true,
          feedback: "Correcto.",
        },
        {
          id: "c",
          text: "Llevar comida.",
          isCorrect: false,
          feedback: "Innecesario.",
        },
      ],
    },
    {
      id: 10,
      text: "¿Habilidad clave en equipo global?",
      options: [
        {
          id: "a",
          text: "Solo inglés.",
          isCorrect: false,
          feedback: "Insuficiente.",
        },
        {
          id: "b",
          text: "Inteligencia Cultural (CQ).",
          isCorrect: true,
          feedback: "Correcto.",
        },
        {
          id: "c",
          text: "Imponer tu cultura.",
          isCorrect: false,
          feedback: "Conflicto.",
        },
      ],
    },
  ],

  fr: [
    {
      id: 1,
      text: "(Pologne) 5 min de retard. Que faire ?",
      options: [
        {
          id: "a",
          text: "Plaisanter.",
          isCorrect: false,
          feedback: "La ponctualité est critique.",
        },
        {
          id: "b",
          text: "S'excuser brièvement.",
          isCorrect: true,
          feedback: "Correct. Soyez professionnel.",
        },
        {
          id: "c",
          text: "Accuser le trafic.",
          isCorrect: false,
          feedback: "Pas professionnel.",
        },
      ],
    },
    {
      id: 2,
      text: "(Pologne) S'adresser à un manager ?",
      options: [
        {
          id: "a",
          text: "Par son prénom.",
          isCorrect: false,
          feedback: "Trop informel.",
        },
        {
          id: "b",
          text: "Pan (M.) / Pani (Mme) + Nom",
          isCorrect: true,
          feedback: "Correct. La formalité compte.",
        },
        {
          id: "c",
          text: "Salut l'ami !",
          isCorrect: false,
          feedback: "Impoli.",
        },
      ],
    },
    {
      id: 3,
      text: "(Espagne) L'heure du déjeuner ?",
      options: [
        {
          id: "a",
          text: "12h00 - 13h00",
          isCorrect: false,
          feedback: "Trop tôt.",
        },
        {
          id: "b",
          text: "Entre 14h00 - 16h00",
          isCorrect: true,
          feedback: "Correct.",
        },
        {
          id: "c",
          text: "Je ne mange pas.",
          isCorrect: false,
          feedback: "Le repas est social.",
        },
      ],
    },
    {
      id: 4,
      text: "(Espagne) On vous coupe la parole :",
      options: [
        {
          id: "a",
          text: "Manque de respect.",
          isCorrect: false,
          feedback: "Pas forcément.",
        },
        {
          id: "b",
          text: "Intérêt et passion.",
          isCorrect: true,
          feedback: "Correct. C'est de l'écoute active.",
        },
        {
          id: "c",
          text: "Envie de dispute.",
          isCorrect: false,
          feedback: "Faux.",
        },
      ],
    },
    {
      id: 5,
      text: "(Maroc) On offre du thé ?",
      options: [
        { id: "a", text: "Refuser.", isCorrect: false, feedback: "Impoli." },
        {
          id: "b",
          text: "Accepter et remercier.",
          isCorrect: true,
          feedback: "Correct. Symbole d'hospitalité.",
        },
        { id: "c", text: "Payer.", isCorrect: false, feedback: "Insultant." },
      ],
    },
    {
      id: 6,
      text: "(Maroc) Quelle main pour manger ?",
      options: [
        {
          id: "a",
          text: "Gauche",
          isCorrect: false,
          feedback: "Considérée impure.",
        },
        { id: "b", text: "Droite", isCorrect: true, feedback: "Correct." },
        {
          id: "c",
          text: "Peu importe.",
          isCorrect: false,
          feedback: "Erreur culturelle.",
        },
      ],
    },
    {
      id: 7,
      text: "(Turquie) Un manager âgé entre.",
      options: [
        {
          id: "a",
          text: "Rester affalé.",
          isCorrect: false,
          feedback: "Irrespectueux.",
        },
        {
          id: "b",
          text: "Se redresser ou se lever.",
          isCorrect: true,
          feedback: "Correct. Respect de la hiérarchie.",
        },
        { id: "c", text: "Partir.", isCorrect: false, feedback: "Faux." },
      ],
    },
    {
      id: 8,
      text: "(Turquie) 'Eline sağlık' signifie :",
      options: [
        {
          id: "a",
          text: "Merci au cuisinier.",
          isCorrect: true,
          feedback: "Correct.",
        },
        {
          id: "b",
          text: "Lave tes mains.",
          isCorrect: false,
          feedback: "Non.",
        },
        {
          id: "c",
          text: "Paye l'addition.",
          isCorrect: false,
          feedback: "Non.",
        },
      ],
    },
    {
      id: 9,
      text: "(Pologne) Visite à domicile.",
      options: [
        {
          id: "a",
          text: "Garder ses chaussures.",
          isCorrect: false,
          feedback: "Non.",
        },
        {
          id: "b",
          text: "Enlever chaussures, offrir cadeau.",
          isCorrect: true,
          feedback: "Correct.",
        },
        {
          id: "c",
          text: "Apporter son repas.",
          isCorrect: false,
          feedback: "Inutile.",
        },
      ],
    },
    {
      id: 10,
      text: "Compétence clé en équipe globale ?",
      options: [
        {
          id: "a",
          text: "Juste l'anglais.",
          isCorrect: false,
          feedback: "Insuffisant.",
        },
        {
          id: "b",
          text: "Intelligence Culturelle (CQ).",
          isCorrect: true,
          feedback: "Correct.",
        },
        {
          id: "c",
          text: "Imposer sa culture.",
          isCorrect: false,
          feedback: "Conflit.",
        },
      ],
    },
  ],

  pl: [
    {
      id: 1,
      text: "(Polska) Spóźniasz się 5 minut na spotkanie. Co robisz?",
      options: [
        {
          id: "a",
          text: "Żartujesz z tego.",
          isCorrect: false,
          feedback: "Punktualność jest kluczowa; żarty są nie na miejscu.",
        },
        {
          id: "b",
          text: "Przepraszasz krótko i siadasz.",
          isCorrect: true,
          feedback: "Dobrze. Oczekuje się profesjonalizmu.",
        },
        {
          id: "c",
          text: "Narzekasz na korki.",
          isCorrect: false,
          feedback: "Wymówki są nieprofesjonalne.",
        },
      ],
    },
    {
      id: 2,
      text: "(Polska) Jak zwracać się do przełożonego?",
      options: [
        {
          id: "a",
          text: "Po imieniu.",
          isCorrect: false,
          feedback: "Zbyt nieformalnie na początku.",
        },
        {
          id: "b",
          text: "Pan / Pani + Nazwisko",
          isCorrect: true,
          feedback: "Dobrze. Formalność jest ważna.",
        },
        {
          id: "c",
          text: "Hej kolego!",
          isCorrect: false,
          feedback: "Niegrzeczne.",
        },
      ],
    },
    {
      id: 3,
      text: "(Hiszpania) Kiedy zazwyczaj jest lunch?",
      options: [
        {
          id: "a",
          text: "12:00 - 13:00",
          isCorrect: false,
          feedback: "Za wcześnie.",
        },
        {
          id: "b",
          text: "Między 14:00 a 16:00",
          isCorrect: true,
          feedback: "Dobrze.",
        },
        {
          id: "c",
          text: "Nie jem lunchu.",
          isCorrect: false,
          feedback: "Jedzenie jest ważne społecznie.",
        },
      ],
    },
    {
      id: 4,
      text: "(Hiszpania) Ktoś Ci przerywa w rozmowie:",
      options: [
        {
          id: "a",
          text: "To brak szacunku.",
          isCorrect: false,
          feedback: "Niekoniecznie.",
        },
        {
          id: "b",
          text: "To oznaka zainteresowania.",
          isCorrect: true,
          feedback: "Dobrze. To aktywne słuchanie.",
        },
        {
          id: "c",
          text: "Chce się kłócić.",
          isCorrect: false,
          feedback: "Źle.",
        },
      ],
    },
    {
      id: 5,
      text: "(Maroko) Oferują Ci herbatę. Co robisz?",
      options: [
        {
          id: "a",
          text: "Odmawiasz.",
          isCorrect: false,
          feedback: "To niegrzeczne.",
        },
        {
          id: "b",
          text: "Przyjmujesz i dziękujesz.",
          isCorrect: true,
          feedback: "Dobrze. To symbol gościnności.",
        },
        {
          id: "c",
          text: "Chcesz zapłacić.",
          isCorrect: false,
          feedback: "Obraźliwe.",
        },
      ],
    },
    {
      id: 6,
      text: "(Maroko) Którą ręką jeść?",
      options: [
        {
          id: "a",
          text: "Lewą",
          isCorrect: false,
          feedback: "Uważana za nieczystą.",
        },
        { id: "b", text: "Prawą", isCorrect: true, feedback: "Dobrze." },
        {
          id: "c",
          text: "Obojętnie.",
          isCorrect: false,
          feedback: "Błąd kulturowy.",
        },
      ],
    },
    {
      id: 7,
      text: "(Turcja) Wchodzi starszy menedżer.",
      options: [
        {
          id: "a",
          text: "Siedzisz zgarbiony.",
          isCorrect: false,
          feedback: "Brak szacunku.",
        },
        {
          id: "b",
          text: "Poprawiasz się lub wstajesz.",
          isCorrect: true,
          feedback: "Dobrze. Szacunek dla hierarchii.",
        },
        { id: "c", text: "Wychodzisz.", isCorrect: false, feedback: "Źle." },
      ],
    },
    {
      id: 8,
      text: "(Turcja) 'Eline sağlık' oznacza:",
      options: [
        {
          id: "a",
          text: "Podziękowanie dla kucharza.",
          isCorrect: true,
          feedback: "Dobrze.",
        },
        { id: "b", text: "Umyj ręce.", isCorrect: false, feedback: "Nie." },
        {
          id: "c",
          text: "Zapłać rachunek.",
          isCorrect: false,
          feedback: "Nie.",
        },
      ],
    },
    {
      id: 9,
      text: "(Polska) Idziesz w gości do domu.",
      options: [
        {
          id: "a",
          text: "Wchodzisz w butach.",
          isCorrect: false,
          feedback: "Zdejmuje się buty.",
        },
        {
          id: "b",
          text: "Zdejmujesz buty, dajesz prezent.",
          isCorrect: true,
          feedback: "Dobrze.",
        },
        {
          id: "c",
          text: "Przynosisz własne jedzenie.",
          isCorrect: false,
          feedback: "Niepotrzebne.",
        },
      ],
    },
    {
      id: 10,
      text: "Kluczowa umiejętność w zespole globalnym?",
      options: [
        {
          id: "a",
          text: "Tylko język angielski.",
          isCorrect: false,
          feedback: "Niewystarczające.",
        },
        {
          id: "b",
          text: "Inteligencja Kulturowa (CQ).",
          isCorrect: true,
          feedback: "Dobrze.",
        },
        {
          id: "c",
          text: "Narzucanie swojej kultury.",
          isCorrect: false,
          feedback: "Konflikt.",
        },
      ],
    },
  ],
};
